[build.env]
passthrough = [
    "PKG_CONFIG_ALLOW_CROSS",
    "PKG_CONFIG_PATH",
]

[target.i686-unknown-linux-gnu]
image = "jaemk/clin-i686-unknown-linux-gnu:v0.1.0"

[target.x86_64-unknown-linux-gnu]
image = "jaemk/clin-x86_64-unknown-linux-gnu:v0.1.0"

